steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['fetch', '--unshallow']
- name: 'node:12.13.1'
  entrypoint: npm
  args: ['run', 'build:prod']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
