export const ROUTE_PREFIX = '/api';
export const ROUTE_TEST_PREFIX = '/api/test';
export const ANGULAR_ROUTE = '/angular';
export const REACT_ROUTE = '/react';
export const CROWD_DJ_ROUTE = '/crowd-dj';
export const CROWD_DJ_LANDING_ROUTE = CROWD_DJ_ROUTE + '/landing';
export const SPOTIFY_LANDING_ROUTE = CROWD_DJ_ROUTE + '/spotify';
export const PODCAST_ROUTE = '/podcasts'
export const SPOTIFY_AUTH_ROUTE = '/spotify/auth'
export const SPOTIFY_REDIRECT_ROUTE = SPOTIFY_AUTH_ROUTE + '/redirect'